name: tokopedia
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.5
  iconly: ^1.0.1
  step_progress_indicator: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/image/
