// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHHFSR3uXxsRl4uI6jR7agb-4nQWqH5rc',
    appId: '1:558362253125:web:b0f84723f9032ae8ed102c',
    messagingSenderId: '558362253125',
    projectId: 'tokopedia-b3552',
    authDomain: 'tokopedia-b3552.firebaseapp.com',
    storageBucket: 'tokopedia-b3552.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDRJ4gLf6U1VQZY92kKK1sqYHaXJ6ROsM',
    appId: '1:558362253125:android:afdb61bd07d4f9cbed102c',
    messagingSenderId: '558362253125',
    projectId: 'tokopedia-b3552',
    storageBucket: 'tokopedia-b3552.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuipjvIa5J_UNrMw60uY6eiKtF6GIL7Uk',
    appId: '1:558362253125:ios:2cd627d9ec64ed84ed102c',
    messagingSenderId: '558362253125',
    projectId: 'tokopedia-b3552',
    storageBucket: 'tokopedia-b3552.appspot.com',
    iosClientId: '558362253125-5rsv0ks6vv4rhhtanp2fmacvrfjuq6fc.apps.googleusercontent.com',
    iosBundleId: 'com.tokopedia.tokopedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuipjvIa5J_UNrMw60uY6eiKtF6GIL7Uk',
    appId: '1:558362253125:ios:2cd627d9ec64ed84ed102c',
    messagingSenderId: '558362253125',
    projectId: 'tokopedia-b3552',
    storageBucket: 'tokopedia-b3552.appspot.com',
    iosClientId: '558362253125-5rsv0ks6vv4rhhtanp2fmacvrfjuq6fc.apps.googleusercontent.com',
    iosBundleId: 'com.tokopedia.tokopedia',
  );
}
